/* auto-generated by NAPI-RS */

export interface JsValue {
  /** The type of the value */
  valueType: string;
  /** String representation of the value */
  value: string;
}

/** A JavaScript engine instance exposed to Node.js. */
export class Engine {
  /** Creates a new JavaScript engine instance. */
  constructor();

  /** Evaluates JavaScript source code and returns the result. */
  eval(source: string): JsValue;

  /** Evaluates JavaScript from a file. */
  evalFile(path: string): JsValue;
}

/** Version information for the spacey-node module. */
export function version(): string;

/** Gets the name of this engine. */
export function engineName(): string;

