// Auto-generated by napi-rs - this is a placeholder
// The actual bindings will be generated during build

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim();
      return readFileSync(lddPath, 'utf8').includes('musl');
    } catch {
      return true;
    }
  } else {
    const report = process.report.getReport();
    const glibcVersion = report?.header?.glibcVersionRuntime;
    return !glibcVersion;
  }
}

const platformArchMap = {
  'darwin-x64': 'darwin-x64',
  'darwin-arm64': 'darwin-arm64',
  'linux-x64-gnu': 'linux-x64-gnu',
  'linux-x64-musl': 'linux-x64-musl',
  'linux-arm64-gnu': 'linux-arm64-gnu',
  'linux-arm64-musl': 'linux-arm64-musl',
  'win32-x64-msvc': 'win32-x64-msvc',
};

function getPlatformKey() {
  if (platform === 'linux') {
    return `${platform}-${arch}-${isMusl() ? 'musl' : 'gnu'}`;
  }
  if (platform === 'win32') {
    return `${platform}-${arch}-msvc`;
  }
  return `${platform}-${arch}`;
}

const platformKey = getPlatformKey();
const tripleName = platformArchMap[platformKey];

if (tripleName) {
  const localPath = join(__dirname, `spacey-node.${tripleName}.node`);
  localFileExisted = existsSync(localPath);

  if (localFileExisted) {
    try {
      nativeBinding = require(localPath);
    } catch (e) {
      loadError = e;
    }
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding for ${platformKey}`);
}

module.exports = nativeBinding;

